version: '3.1'

services:
  gtfs_warszawa:
    build:
      dockerfile: Dockerfile.warszawa
    container_name: gtfs_warsaw
    ports:
      - '8082:8080'
    environment:
      - JAVA_OPTS=-Xmx4G

  gtfs_krakow:
    build:
      dockerfile: Dockerfile.krakow
    container_name: gtfs_krakow
    ports:
      - '8084:8080'
    environment:
      - JAVA_OPTS=-Xmx1G

  gtfs_wroclaw:
    build:
      dockerfile: Dockerfile.wroclaw
    container_name: gtfs_wroclaw
    ports:
      - '8088:8080'
    environment:
      - JAVA_OPTS=-Xmx1G

  gtfs_cyprus:
    build:
      dockerfile: Dockerfile.cyprus
    container_name: gtfs_cyprus
    ports:
      - '8086:8080'
    environment:
      - JAVA_OPTS=-Xmx2G
