version: '3.1'

services:
  gtfs_warsaw:
    build:
#      context: warsaw/
      dockerfile: Dockerfile
    container_name: gtfs_warsaw
    ports:
      - '8082:8080'
    environment:
      - JAVA_OPTS=-Xmx3G
