version: '3.1'

services:
  gtfs_warszawa:
    build:
      dockerfile: Dockerfile.warszawa
    container_name: gtfs_warsaw
    ports:
      - '8082:8080'
    environment:
      - JAVA_OPTS=-Xmx3G

  gtfs_krakow:
    build:
      dockerfile: Dockerfile.krakow
    container_name: gtfs_krakow
    ports:
      - '8084:8080'
    environment:
      - JAVA_OPTS=-Xmx1G
