name: GTFS Deploy

on:
  workflow_dispatch:
    inputs:
      city:
        type: choice
        options:
          - warszawa
          - krakow
          - cyprus

  workflow_call:
    inputs:
      city:
        required: true
        type: string

env:
  DOCKER_REGISTRY: registry.digitalocean.com/igeolab
  DOCKER_FILE: Dockerfile.${{ inputs.city }}
  DOCKER_TAG: public-transport/otp-${{ inputs.city }}:1.0.0

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build GTFS docker image
        run: docker build -t ${{ env.DOCKER_TAG }} -f ${{ env.DOCKER_FILE }} .

      - name: Tag Image
        run: docker tag ${{ env.DOCKER_TAG }} ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_TAG }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Deploy docker image
        run: docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_TAG }}

  k8s:
    runs-on: ubuntu-latest
    needs: [ docker ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
