name: GTFS Schedule

on:
  schedule:
    - cron: "50 19 * * *"

jobs:
  warszawa-gtfs:
    uses: .github/workflows/deploy-docker.yml@main
    with:
      city: warszawa
    secrets: inherit
  krakow-gtfs:
    uses: deploy-docker.yml@main
    with:
      city: krakow
    secrets: inherit
