name: Warsaw GTFS

on:
  workflow_dispatch:

env:
  REGISTRY: registry.digitalocean.com/igeolab
  DOCKER_TAG: public-transport/otp-warsaw:1.0.0

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build docker Warsaw GTFS
        run: cd docker/warsaw/ && docker build -t ${{ env.DOCKER_TAG }} .

      - name: Tag Image
        run: docker tag ${{ env.DOCKER_TAG }} ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_TAG }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Deploy docker image
        run: docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_TAG }}

      - name: Clear registry
        run: doctl registry garbage-collection start --include-untagged-manifests igeolab --force
