name: GTFS Schedule

on:
  schedule:
    - cron: "45 19 * * *"

jobs:
  warszawa-gtfs:
    uses: deploy-docker.yml@main
    with:
      city: warszawa
    secrets: inherit
  krakow-gtfs:
    uses: deploy-docker.yml@main
    with:
      city: krakow
    secrets: inherit
