name: GTFS Schedule

on:
  schedule:
    - cron: "10 20 * * *"

jobs:
  warszawa-gtfs:
    uses: ./.github/workflows/deploy-docker.yml
    with:
      city: warszawa
    secrets: inherit
  krakow-gtfs:
    uses: ./.github/workflows/deploy-docker.yml
    with:
      city: krakow
    secrets: inherit
