name: GTFS Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "00 22 * * *"

jobs:
  warszawa-gtfs:
    uses: ./.github/workflows/deploy-docker.yml
    with:
      city: warszawa
    secrets: inherit
  krakow-gtfs:
    uses: ./.github/workflows/deploy-docker.yml
    with:
      city: krakow
    secrets: inherit

  clean:
    uses: ./.github/workflows/deploy-clean.yml
    secrets: inherit
